### PR TITLE
struct-reader.h: do not name a temporal variable

### PR DESCRIPTION
**Pull request by pavelkryukov**

### CODE REVIEW

**Comment by alexpolt** [comment]
Pavel, big thanks for your time. Just one question before I merge your pull requests. Have you checked it on MSVC compiler? I ask because I vaguely remember I had problems with it. :)

**Comment by pavelkryukov** [comment]
I wrote a tiny test file: https://github.com/pavelkryukov/luple/blob/test/test.cpp
Compilation with VS 19.14.26430 is successful if both my pull requests are merged.

**Comment by alexpolt** [comment]
BTW, just so you know, if you have access to C++17 then I suggest taking a look at a more stable solution from Antony Polukhin [](https://www.youtube.com/watch?v=UlNUNxLtBI0) (should add that link to readme).

**Comment by pavelkryukov** [comment]
Thanks!
Actually, it's quite tricky to google/stackoverflow those things, everything ends up in "C++ has no reflection, point" or in your blog post about `struct_reader`. For instance, I noticed the `loophole` while submitting this PR.

The more crazy magic I'm thinking of is to generate a list of pointers-to-members for a specific structure. Probably, it can be extracted from `loophole` or similar output with some casting exercises.

**Comment by alexpolt** [comment]
Yes. That's why I created luple. It's a tuple that uses multiple inheritance and its data layout is exactly that of a data struct, so I can just give it the type list from loophole and then use things like luple_do to iterate over members. Like that:
`struct data {
  float a;
  std::string b;
};

using data_tlist = loophole_ns::as_type_list< data >;
using data_luple = luple_t< data_tlist >;
alignas(alignof(data)) char d[sizeof(data)];
auto& l = reinterpret_cast< data_luple& >( d );
get<std::string>(l) = "Hello World!"
get<0>(l) = 1.f;
luple_do( l, []( auto& value ) { std::cout << value << "\n"; } );`

**Pull request merged**
